### ISSUE TITLE
convert_gfx.sh error

### ISSUE THREAD

**Issue by LBS71** [meeq/FlappyBird-N64#1]
hello,
when i try to compile this project i have a error : 

/usr/local/libdragon/bin/mips64-elf-ld -o FlappyBird.elf src/background.o src/pipes.o src/ui.o src/system.o src/audio.o src/fps.o src/main.o src/collision.o src/bird.o src/graphics.o --library=dragon --library=c --library=m --library=dragonsys -L/usr/local/libdragon/lib -L/usr/local/libdragon/mips64-elf/lib --script=/usr/local/libdragon/mips64-elf/lib/n64ld.x
/usr/local/libdragon/bin/mips64-elf-objcopy -O binary FlappyBird.elf FlappyBird.bin
sh ./convert_gfx.sh resources/gfx/ground.png
./convert_gfx.sh: 36: ./convert_gfx.sh: Syntax error: "(" unexpected (expecting "}")
Makefile:129: recipe for target 'filesystem/gfx/ground.sprite' failed
make: *** [filesystem/gfx/ground.sprite] Error 2

Could you help me ?

thanks

**Comment by meeq** [comment]
I cannot reproduce this error, but my guess is that this is caused by the Makefile calling `convert_gfx.sh` using `sh` when it should be explicitly using `bash`.

I have made some portability fixes in 68453d62b093f132aa32ff4953b7c28a7c9788cd which should hopefully resolve this issue (as well as building on OS X). If not, please let me know a bit more about your environment so I can dig in deeper.

**Comment by LBS71** [comment]
Great !!!!! It s ok.




Thank you very much






Télécharger Outlook pour Android







On Fri, Jul 7, 2017 at 4:44 PM +0200, "Christopher Bonhage" <notifications@github.com> wrote:












I cannot reproduce this error, but my guess is that this is caused by the Makefile calling convert_gfx.sh using sh when it should be explicitly using bash.


I have made some portability fixes in 68453d6 which should hopefully resolve this issue (as well as building on OS X). If not, please let me know a bit more about your environment so I can dig in deeper.
